CREATE DATABASE ToDoListDB;

USE ToDoListDB;

CREATE TABLE users (
	id INT PRIMARY KEY IDENTITY(1,1),
	username VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	password_hash VARCHAR(255) NOT NULL,
	created_at DATETIME DEFAULT GETDATE(),
	updated_at DATETIME DEFAULT GETDATE()
);

CREATE TABLE tasks (
	id INT PRIMARY KEY IDENTITY(1,1),
	user_id INT NOT NULL,
	title VARCHAR(255) NOT NULL,
	description TEXT,
	status VARCHAR(50) NOT NULL,
	priority TINYINT NOT NULL,
	due_date DATETIME NOT NULL,
	created_at DATETIME DEFAULT GETDATE(),
	updated_at DATETIME DEFAULT GETDATE(),

	FOREIGN KEY (user_id) REFERENCES users(id)
);